### ISSUE TITLE
ability to move "request for change" link

### ISSUE THREAD

**Issue by petermixt** [code4recovery/12-step-meeting-list-feedback-enhancement#18]
Would be nice to move the "update" link to the bottom of the left column?  Current location is too handy for the public to click and send.

**Comment by kiyote33** [comment]
Exactly what we are trying to achieve. Keep it simple so the public can easily see meeting details and then submit a change request for the meeting. Can you expand on the logic for not having it be handy? I haven't heard an argument in favor of less usability, so I am interested in your thoughts...

**Comment by petermixt** [comment]
Currently the "Request a change to this listing" is at the top of the detail page above the map.  It shows even if the meeting is online and the map does not show. It sits there naked.  Could this link be re-located to the bottom of the "Meeting Information"  window on the left side (as it is on the TSML-UI Display), but still target the same frame it currently populates when activated.  

Yes it is now easy to find -- maybe too easy for the bored fellowship member to just click and play.

**Comment by kiyote33** [comment]
Hi Peter,

 

Your request is certainly doable. Let’s discuss it with the rest of the team and see what other’s think. I’m not married to the current setup, but my preference is to leave as is…

 

Wayne
