### ISSUE TITLE
Meetings At This Location feature broken

### ISSUE THREAD

**Issue by degrees57** [code4recovery/12-step-meeting-list-feedback-enhancement#23]
If I disable the 12 Step Meeting List Feedback Enhancement plugin and visit a meeting on the web site, the third block down is the Location name and a counter "18 other meetings at this location" (for example).  If I click on that block, it takes me to a page under /locations/ for that location, and lists all the meeting times and names there.

If I enable the 12 Step Meeting List Feedback Enhancement plugin, and click the block, the URL remains the same as before, but the Location page looks like it opened a new, single empty meeting, with nothing but:

Meeting Information
Appointment
In-person

I've tried deactivating most of the plugins I have that I think could potentially interfere, but I still see the same behavior: without the 12 Step Meeting List Feedback Enhancement plugin, the Locations page generates a list, but with it, the Locations page stumbles on a single empty something or other.

**Comment by rockridgefellowship** [comment]
Hi there! I'm also experiencing this issue, as described by @degrees57

**Comment by kiyote33** [comment]
Need to re-sync code base with current version of TSML. Will fix in next release.
