### ISSUE TITLE
Goes to email

### ISSUE THREAD

**Issue by dougie-wougie** [code4recovery/12-step-meeting-list-feedback-enhancement#28]
Just added the Enhancement plugin. Cool idea. I open a meeting and click the update button. It opens my email client. It was my understanding it would replace the map and give all the cool stuff to be able to change, which then would be emailed. I am not sure why I am not getting the enhancements.

What do you need from me? the site is test only. dougwade.com I hope to release it at the end of the month after the CO board approves it.

**Comment by kiyote33** [comment]
Sorry about not monitoring this issue reporting more closely. Are you still having a problem. Sounds like you need to enter an email address under the Settings Email Feedback to activate the Feedback Enhancement screen.

**Comment by dougie-wougie** [comment]
It is all good. I updated one meeting, then saved it, and it all works. The site was moved into active use under a different domain name.
